#!/usr/bin/python3
# Purpose: Workstation Menu
# Version: 0.4
######################################################################################

################
# Modules
################
from os import system
from time import sleep

################
# Functions
################
def main():
	choice = '0'
	while choice == '0':
		system("/usr/bin/clear")
		print("=======================================================================")
		print("|| Juniper SRX Demo Kit: Lubuntu Menu                                ||")
		print("=======================================================================")
		print("1) WebFilter Demo: Launch browser with blocked sites tabs")
		print("2) WebFilter Demo: Start permitted traffic generator ")
		print("3) AntiVirus Demo: Download Test Viri ")
		print("4) Content Filter Demo: Download Files with Blocked Extensions ")
		print("5) Content Filter Demo: Launch browser with Blocked Extension sites ")
		print("6) IDP Packetlog Demo: Start PCAP Receiver ")
		print("7) UserFW Demo: Rerun login script to populate vSRX auth-table ")
		print("8) LocalWebFilter Demo: Launch browser with blocked sites tabs ")
		print("\nq) Quit the menu")
		print("=======================================================================")
		choice = input("\nPlease select a menu item: ")

		if choice == "1":
			system("/usr/bin/clear")
			print("....Opening web browser...please wait a few seconds...")
			sleep(3)
			system("/usr/local/bin/open-webfilter-sites.py 2>/dev/null")
			main()
		if choice == "2":
			system("/usr/bin/clear")
			print("....Starting traffic generator...please wait a few seconds...")
			sleep(3)
			system("/usr/bin/lxterminal --command=\"/usr/local/bin/webTrafficGen.py\" 2>/dev/null")
			main()
		if choice == "3":
			system("/usr/bin/clear")
			print("....Starting Virus Downloader...please wait a few seconds...")
			sleep(3)
			system("/usr/bin/lxterminal --geometry=90x20 --command=\"/usr/local/bin/virus-download.py\" 2>/dev/null")
			main()
		if choice == "4":
			system("/usr/bin/clear")
			print("....Starting to download files with restricted extensions...please wait a few seconds...")
			sleep(3)
			system("/usr/bin/lxterminal --geometry=90x20 --command=\"/usr/local/bin/bad-extension-download.py\" 2>/dev/null")
			main()
		if choice == "5":
			system("/usr/bin/clear")
			print("....Opening web browser...please wait a few seconds...")
			sleep(3)
			system("/usr/local/bin/open-contentfilter-sites.py 2>/dev/null")
			main()
		if choice == "6":
			system("/usr/bin/clear")
			print("....Starting PCAP Receiver for IDP Capture...please wait a few seconds...")
			sleep(3)
			system("/usr/bin/lxterminal --geometry=90x20 --command=\"/usr/local/bin/srx_pcap_receiver.py -o /tmp/Juniper_IDP_PCAP_Storage -vv\" 2>/dev/null")
			main()
		if choice == "7":
			system("/usr/bin/clear")
			print("....Populating auth-table on vSRX...please wait a few seconds...")
			sleep(3)
			system("/usr/local/bin/update-local-userfw.py")
			main()
		if choice == "8":
			system("/usr/bin/clear")
			print("....Opening web browser...please wait a few seconds...")
			sleep(3)
			system("/usr/local/bin/open-localwebfilter-sites.py 2>/dev/null")
			main()
		elif choice == "q":
			print("Exiting...")
			exit()
		else:
			print("Invalid option...")
			sleep(3)
			system("/usr/bin/clear")
			main()

main()

## End of Script ##
